import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Tailwind-Document</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='dark:text-6xl dark:text-red-900'>HI</h1>
    </>
  );
}
